### ISSUE TITLE
TypeError: Cannot read property 'pause' of undefined

### ISSUE THREAD

**Issue by Benargee** [alxhotel/chromecast-api#34]
After following the basic example I can not get any kind of interaction to work with my chromecast from this api. I can verify that device is defined as when it is returned in callback from client.on('device', callback). I confirm that device.friendlyName is the name of the chromecast I expected.

I can not get any of prototype/class device function/methods to be recognized. Same issue with client.setVolume(). 

Here is returned error from VS Code
`
Exception has occurred: TypeError
TypeError: Cannot read property 'setVolume' of null
    at Device.setVolume (e:\dev\test\node-chromecast\node_modules\chromecast-api\lib\device.js:229:17)
    at Client.<anonymous> (e:\dev\test\node-chromecast\src\index.js:15:12)
    at Client.emit (events.js:223:5)
    at Client._updateDevice (e:\dev\test\node-chromecast\node_modules\chromecast-api\lib\client.js:40:10)
    at onEachAnswer (e:\dev\test\node-chromecast\node_modules\chromecast-api\lib\client.js:66:46)
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (e:\dev\test\node-chromecast\node_modules\chromecast-api\lib\client.js:95:28)
    at EventEmitter.emit (events.js:223:5)
    at Socket.<anonymous> (e:\dev\test\node-chromecast\node_modules\multicast-dns\index.js:49:43)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)
`

I am using 3rd gen Chromecast.
process.versions.node = "12.14.1"

Let me know of any other information you may need to help fix this issue. Is there any other kind of setup i'm missing? Does the device have to be in debug mode? I mean, the device is recognised by this api, I just cant interact with it besides detection.

Edit: Back to this example:
```js
const ChromecastAPI = require('chromecast-api')
 
const client = new ChromecastAPI()
 
client.on('device', function (device) {
  var mediaURL = 'http://commondatastorage.googleapis.com/gtv-videos-bucket/big_buck_bunny_1080p.mp4';
 
  device.play(mediaURL, function (err) {
    if (!err) console.log('Playing in your chromecast')
  })
})
```

No errors but nothing happens. The chromecast is at the idle screen too.

**Comment by Benargee** [comment]
It seems like after I installed npm [mdns](https://www.npmjs.com/package/mdns) properly, all my problems went away. I had to make sure I had python 2.7 installed, Bonjour SDK for Windows 3.0 installed, ensure BONJOUR_SDK_HOME environmental variable was set correctly, install Windows Build Tools 2015, restarted my PC, cleared my AppData/Local/node-gyp/cache folder, ran npm install mdns and everything worked out. Now this api and the example from npm [castv2-client](https://www.npmjs.com/package/castv2-client) work perfectly.
Closing this issue as I have resolved it.
